services:
  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"  # Redisのポート
    volumes:
      - redis_data:/data # Redisのデータを保存する場所

  worker:
    build:
      context: ./worker
    container_name: worker
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    volumes:
      - ./worker:/app
    restart: always

volumes:
  redis_data:
